"""Create initial tables

Revision ID: 3a556e4deb48
Revises: 3ae25c851e17
Create Date: 2025-06-21 19:54:01.072543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a556e4deb48'
down_revision: Union[str, Sequence[str], None] = '3ae25c851e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'website')
    # ### end Alembic commands ###
