"""Create initial tables

Revision ID: 3ae25c851e17
Revises: c80f611f92db
Create Date: 2025-06-21 19:38:59.806258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae25c851e17'
down_revision: Union[str, Sequence[str], None] = 'c80f611f92db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'website')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
