"""Create initial tables

Revision ID: 50aa24dffe39
Revises: 3a556e4deb48
Create Date: 2025-06-22 20:28:58.529368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50aa24dffe39'
down_revision: Union[str, Sequence[str], None] = '3a556e4deb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_foreign_key(None, 'business', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'business_details', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'contact', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'media', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_constraint(None, 'business_details', type_='foreignkey')
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
